[package]
name = "dtolnay"
version = "0.0.8"
authors = ["David Tolnay <dtolnay@gmail.com>"]
license = "MIT OR Apache-2.0"
description = "docs.rs as a publishing platform?"
repository = "https://github.com/dtolnay/essay"
documentation = "https://docs.rs/dtolnay"
edition = "2018"

[badges]
travis-ci = { repository = "dtolnay/essay" }

[dev-dependencies]
futures = "0.1"
